enable NFS support
AntonioMeireles/vagrant-guests-clearlinux pull request #1
Opened 2018-11-15 08:05 UTC by ganeshmaharaj

Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

2018-11-15 10:00 UTC, AntonioMeireles commented
@ganeshmaharaj 

Hi, **MANY**, **MANY** thanks for this ...

i've added already some comments... won' t be able probably to test / merge before next week as i'm in the _road_ (in Vacouver at SURICON) 


Best Regards, 

António

2018-11-15 15:35 UTC, ganeshmaharaj commented
@AntonioMeireles thanks. Take your time on the merge. I was not able to spot the comments youi had added on the patch. Will check for it next week once you are back from your travel.

2018-11-19 12:00 UTC, AntonioMeireles requested changes
@ganeshmaharaj 

(back in Portugal :-) ) clarified my comments. 

basically it's just the `"swupd bundle-add storage-utils",` that is superfluous. 

Other than that, and at sight all will looks fine. 

thanks again!

2018-11-19 12:00 UTC, AntonioMeireles commented on lib/vagrant-guests-clearlinux/cap/nfs_client.rb
> +            "swupd bundle-add storage-utils",
invoking `swupd bundle-add storage-utils` here is redundant as the `storage-utils` bundle is **always** available unconditionally, by Default, in the stock ClearLinux vagrant boxes we publish.

2018-11-21 20:47 UTC, ganeshmaharaj commented on lib/vagrant-guests-clearlinux/cap/nfs_client.rb
> +            "swupd bundle-add storage-utils",
@AntonioMeireles the kvm images did not have those when i checked the last time. Are you adding them as part of your packaging or does the vmdk images have them?

2018-11-21 20:48 UTC, ganeshmaharaj commented
@AntonioMeireles should give you some background along with this. I realized that we didn't have a libvirt image for clearlinux and i started creating them https://app.vagrantup.com/gmmaha/boxes/clearlinux

2018-11-21 21:28 UTC, AntonioMeireles commented
ah... do you have the source available for those?... would make sense to
just add libvirt support to my pipeline (was on my todo list already).
Patches welcome ;-). in the meantime, given that, i'll merge your patch as
is (when near my laptop). plz do note that the guest plugin makes a lots of
assumptions about how the boxes are built (plz see my packer tooling) that
you should follow, otherwise you may get some undesired "features".

all the best,


António

On Wed, 21 Nov 2018 at 20:48, Ganesh Maharaj Mahalingam <
notifications@github.com> wrote:

> @AntonioMeireles <https://github.com/AntonioMeireles> should give you
> some background along with this. I realized that we didn't have a libvirt
> image for clearlinux and i started creating them
> https://app.vagrantup.com/gmmaha/boxes/clearlinux
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AntonioMeireles/vagrant-guests-clearlinux/pull/1#issuecomment-440803769>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAtYZzUluoXjYDR0GubPzrGkGr64_8aCks5uxbwAgaJpZM4YfRow>
> .
>

2018-11-21 21:32 UTC, ganeshmaharaj commented
@AntonioMeireles absolutely. https://github.com/ganeshmaharaj/clearlinux/blob/master/libvirt-box/gen_vagrant_libvirt.sh that is the simple script that builds the libvirt box for me. Yes, i was going to look at your packer tooling and get libvirt going, but time crunch and shell script was an easy way. I will definitely work on moving it into your tooling. The guest plugin does work perfectly with the KVM image as of today (The couple of use-cases i have tested it).

2018-11-22 10:23 UTC, merged

2018-11-22 10:30 UTC, AntonioMeireles commented
@ganeshmaharaj it's in ... v1.0.14 is out and pushed to rubygems.org. 

please report back if anything odd arises. 

**THANKS**!

2018-11-22 15:25 UTC, ganeshmaharaj commented
@AntonioMeireles thank you so much. I will definitely let you know.